run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 15
    skip-tests: true
  lll:
    line-length: 160
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G601

linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - exportloopref # deprecated
    - gocyclo # duplicate of cyclop
    - gomnd # deprecated
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - mnd
    - gomoddirectives
    - intrange
    - ireturn
    - nlreturn
    - nilnil
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
