version: "2"
run:
  tests: false

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - gocyclo # duplicate of cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomoddirectives
    - intrange
    - ireturn
    - mnd
    - nilnil
    - nlreturn
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    gosec:
      excludes:
        - G601
    lll:
      line-length: 160
  exclusions:
    generated: lax
