package testdata

// Code generated by oapi-gen. DO NOT EDIT.

// Docs returns a set of property descriptions per property.
func (TestObject) Docs() map[string]string {
	return map[string]string{
		"B": "B is another example field.",
		"a": "A is an example field with &#34;quotes&#34;.",
	}
}

// Attributes returns a set of property attributes per property.
func (TestObject) Attributes() map[string]string {
	return map[string]string{
		"B": "required",
	}
}

// Docs returns a set of property descriptions per property.
func (TestOtherObject) Docs() map[string]string {
	return map[string]string{
		"D": "D is another example field.",
		"c": "C is an example field.",
	}
}

// Attributes returns a set of property attributes per property.
func (TestOtherObject) Attributes() map[string]string {
	return map[string]string{
		"D": "readonly",
	}
}
