// Code generated by oapi-gen. DO NOT EDIT.

package testdata

// Docs returns a set of property descriptions per property.
func (TestObject) Docs() map[string]string {
	return map[string]string{
		"B": "B is another example field.",
		"a": "A is an example field with &#34;quotes&#34;\nand a newline.",
	}
}

// Attributes returns a set of property attributes per property.
func (TestObject) Attributes() map[string]string {
	return map[string]string{
		"B": "required",
	}
}

// Docs returns a set of property descriptions per property.
func (TestOtherObject) Docs() map[string]string {
	return map[string]string{
		"D": "D is another example field.",
		"E": "E is a formatted example field.",
		"F": "F is a field that uses enum values.",
		"c": "C is an example field.",
	}
}

// Attributes returns a set of property attributes per property.
func (TestOtherObject) Attributes() map[string]string {
	return map[string]string{
		"D": "readonly",
	}
}

// Formats returns a set of property formats per property.
func (TestOtherObject) Formats() map[string]string {
	return map[string]string{
		"E": "ipv4",
	}
}

// Enums returns a set of possible enum values per property.
func (TestOtherObject) Enums() map[string][]string {
	return map[string][]string{
		"F": {"foo", "bar"},
	}
}
